name: Deploy to main
on: repository_dispatch

jobs:
  deploy: 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12'
      - run: yarn global add gatsby-cli gh-pages
      - run: yarn install
      - run: yarn deploy

